#include "ProjectTags.h"

// GAS
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_CHANGE, "Mutant.Change");
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_CHANGE_ACTIVE, "Mutant.Change.Active");

UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_RESTORE, "Mutant.Restore");
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_RESTORE_ACTIVE, "Mutant.Restore.Active");

UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_SKILL_CD, "Mutant.Skill.CD");
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_SKILL_ACTIVE, "Mutant.Skill.Active");

UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_ABILITY_TANK_MAIN, "Mutant.Ability.Tank.Main");
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_ABILITY_GHOST_MAIN, "Mutant.Ability.Ghost.Main");
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_ABILITY_SMOKER_MAIN, "Mutant.Ability.Smoker.Main");
UE_DEFINE_GAMEPLAY_TAG(TAG_MUTANT_ABILITY_CUTTER_MAIN, "Mutant.Ability.Cutter.Main");

// UI
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_GAME, "UI.Layer.Game");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_MENU, "UI.Layer.Menu");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_SERVER, "UI.Layer.Server");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_MODAL, "UI.Layer.Modal");
