#include "ProjectTags.h"

// Combat
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_EQUIPMENT_SWAP, "Ability.Equipment.Swap");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_EQUIPMENT_DROP, "Ability.Equipment.Drop");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_EQUIPMENT_AIM, "Ability.Equipment.Aim");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_WEAPON_FIRE, "Ability.Weapon.Fire");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_WEAPON_RELOAD, "Ability.Weapon.Reload");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_WEAPON_RELOAD_SHOTGUN, "Ability.Weapon.Reload.Shotgun");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MELEE_ATTACK, "Ability.Melee.Attack");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_THROWING_THROW, "Ability.Throwing.Throw");

UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_COMBAT_SWAPPING, "State.Combat.Swapping");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_COMBAT_AIMING, "State.Combat.Aiming");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_COMBAT_RELOADING, "State.Combat.Reloading");

UE_DEFINE_GAMEPLAY_TAG(TAG_GC_EQUIPMENT_SWAPOUT, "GameplayCue.Equipment.SwapOut"); // GC标签是向上冒泡的，触发子标签，会连带触发父标签
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_EQUIPMENT_SWAPOUTREVERSE, "GameplayCue.Equipment.SwapOutReverse");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_EQUIPMENT_SWAPIN, "GameplayCue.Equipment.SwapIn");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_EQUIPMENT_DROP, "GameplayCue.Equipment.Drop");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_WEAPON_FIRE, "GameplayCue.Weapon.Fire");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_WEAPON_DRYFIRE, "GameplayCue.Weapon.DryFire");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_WEAPON_RELOAD, "GameplayCue.Weapon.Reload");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_WEAPON_RELOADEND, "GameplayCue.Weapon.ReloadEnd");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_MELEE_ATTACK, "GameplayCue.Melee.Attack");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_THROWING_THROW, "GameplayCue.Throwing.Throw");

UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_EQUIPMENT_SWAP, "Event.Equipment.Swap"); // 触发GA
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_EQUIPMENT_SWAPOUT_END, "Event.Equipment.SwapOut.End");
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_EQUIPMENT_SWAPIN_END, "Event.Equipment.SwapIn.End");
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_EQUIPMENT_DROP, "Event.Equipment.Drop"); // 触发GA
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_WEAPON_FIRE, "Event.Weapon.Fire");
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_WEAPON_RELOAD_END, "Event.Weapon.Reload.End");
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_WEAPON_RELOAD_INSERT, "Event.Weapon.Reload.Insert");
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_MELEE_ATTACK, "Event.Melee.Attack"); // 触发GA
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_MELEE_RELEASED, "Event.Melee.Released"); // 鼠标释放
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_MELEE_FIRSTSECTIONEND, "Event.Melee.FirstSectionEnd");
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_THROWING_THROWOUT, "Event.Throwing.ThrowOut");

// Human
UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_DNA_EnhancedVision, "State.DNA.EnhancedVision");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_DNA_HighBoneDensity, "State.DNA.HighBoneDensity");

// Mutant
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_CHANGE, "Ability.Mutant.Change");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_RESTORE, "Ability.Mutant.Restore");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_ATTACK, "Ability.Mutant.Attack");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_TANK, "Ability.Mutant.Tank");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_GHOST, "Ability.Mutant.Ghost");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_SMOKER, "Ability.Mutant.Smoker");
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MUTANT_CUTTER, "Ability.Mutant.Cutter");

UE_DEFINE_GAMEPLAY_TAG(TAG_CD_MUTANT_SKILL, "Cooldown.Mutant.Skill");

UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_MUTANT_CHANGING, "State.Mutant.Changing");
UE_DEFINE_GAMEPLAY_TAG(TAG_STATE_MUTANT_SMOKER_SMOKING, "State.Mutant.Smoker.Smoking") // 添加到GE上的标签

UE_DEFINE_GAMEPLAY_TAG(TAG_GC_MUTANT_TANK_SKILL, "GameplayCue.Mutant.Tank.Skill");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_MUTANT_GHOST_SKILL, "GameplayCue.Mutant.Ghost.Skill");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_MUTANT_SMOKER_SKILL, "GameplayCue.Mutant.Smoker.Skill");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_MUTANT_CUTTER_SKILL, "GameplayCue.Mutant.Cutter.Skill");
UE_DEFINE_GAMEPLAY_TAG(TAG_GC_MUTANT_RESTORE, "GameplayCue.Mutant.Restore");

UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_MUTANT_ATTACK_START, "Event.Mutant.Attack.Start"); // 触发GA
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_MUTANT_ATTACK_RELEASED, "Event.Mutant.Attack.Released"); // 鼠标释放
UE_DEFINE_GAMEPLAY_TAG(TAG_EVENT_MUTANT_ATTACK_FIRSTSECTIONEND, "Event.Mutant.Attack.FirstSectionEnd");

// UI
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_GAME, "UI.Layer.Game");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_MENU, "UI.Layer.Menu");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_SERVER, "UI.Layer.Server");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_MODAL, "UI.Layer.Modal");
